### ISSUE TITLE
Generate Extension Headers

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Headers#113]
I'm mostly raising this issue for awareness and to avoid duplicated work.

I started experimenting with generated extension headers using the cl.xml file over the weekend and I'm pretty close to having something workable.  In addition to the nice consistency benefits, this also provides a mechanism to validate that the XML file is correct for extensions, and enables easy additions for things like a symbolic name for extensions (#111) and preprocessor defines for extensions (#86).

Note that I've only done extension headers for now, and not the core API headers.  The extension headers were easier (fewer conditional rules) and are faster moving, so I think they provide a bigger bang-for-the-buck, and I don't plan to generate the core API headers at this time.

The few issues I still need to resolve are:

- [ ] What should we do for the extensions that require external headers, such as the GL, EGL, and DX extensions?  It's easy enough to omit them from the final generated headers, or we could consider a way to describe these extensions without external header dependencies.  (I know how to do this mostly - PR soon.)
- [x] The Intel extensions are in their own file with a unique copyright header.  I'll look into this.  (Fixed by #129).
- [x] I need to figure out how to add the special-case handling for `CL_DEVICE_DOUBLE_FP_CONFIG` (only for pre-OpenCL 1.2) and `cl_kernel_sub_group_info` (only for pre-OpenCL 2.1).  (See https://github.com/KhronosGroup/OpenCL-Docs/issues/463, https://github.com/KhronosGroup/OpenCL-Docs/pull/469)
- [ ] It looks like the macros for `cl_khr_extended_versioning` are not in the XML file, so they need to be added and I need to figure out how to properly generate code for them.  (I know how to do this - PR soon.)
- [x] Decide what to do with `cl_gl_ext.h` (see #145, fixed by #156).
- [ ] Ensure extension API prefix and suffixes are correct and consistent (see #153, #158).

**Comment by kpet** [comment]
That's awesome! This would be a big enabler :).

Regarding the missing `cl_khr_extended_versioning` definitions, I think it's mostly because we still haven't merged the spec PR (https://github.com/KhronosGroup/OpenCL-Docs/pull/218).

**Comment by bashbaug** [comment]
I think I got this mostly working over the holidays.  I found a few additional minor issues (see #145 and #146) but I'm able to generate headers that pass all of the header tests now.  Yay!

My plan is to create a PR with my remaining XML changes shortly, since they're needed to do the generation properly.  I'll follow that with a PR in this repo with the generation change themselves next.  I'll wait for at least #129 to be merged first since it is a pre-requisite, but I can do a draft PR sooner if that would be helpful.  Thanks!
